name: Docs
on:
  push:
    branches:
      - master
jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: git-dev
          inputFile: README.md
          toc: true
          vimVersion: "Neovim verion 0.9"
          description: ""
          demojify: true
          treesitter: true
          shiftheadinglevelby: -1
          docmapping: true
      - name: Generate help tags
        run: nvim --headless --clean -c "helptags doc/" -c qa
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto generate"
          branch: ${{ github.head_ref }}
          file_pattern: doc
